export const sevenNationArmyMelody = [
  { time: 0, notes: ['E3'], duration: '4n.' },
  { time: '0:1:2', notes: ['E3'], duration: '8n' },
  { time: '0:2', notes: ['G3'], duration: '8n.' },
  { time: '0:2:3', notes: ['E3'], duration: '8n.' },
  { time: '0:3:2', notes: ['D3'], duration: '8n' },
  { time: '1:0', notes: ['C3'], duration: '2n' },
  { time: '1:2', notes: ['B2'], duration: '2n' },
  { time: '2:0', notes: ['E3'], duration: '4n.' },
  { time: '2:1:2', notes: ['E3'], duration: '8n' },
  { time: '2:2', notes: ['G3'], duration: '8n.' },
  { time: '2:2:3', notes: ['E3'], duration: '8n.' },
  { time: '2:3:2', notes: ['D3'], duration: '8n' },
  { time: '3:0', notes: ['C3'], duration: '8n.' },
  { time: '3:0:3', notes: ['D3'], duration: '8n.' },
  { time: '3:1:2', notes: ['C3'], duration: '8n' },
  { time: '3:2', notes: ['B2'], duration: '2n' },
];

export const babySharkMelody = [
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['E3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['E3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F#3'], duration: '2n' },
  { notes: ['D3'], duration: '4n' },
  { notes: ['E3'], duration: '4n' },
];

export const inTheEndMelody = [
  { notes: ['E3'], duration: '4n' },
  { notes: ['B3'], duration: '4n' },
  { notes: ['B3'], duration: '4n' },
  { notes: ['G3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E3'], duration: '4n' },
  { notes: ['B3'], duration: '4n' },
  { notes: ['B3'], duration: '4n' },
  { notes: ['G3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
]

export const smellsLikeTeenSpiritMelody = [
  { notes: ['A2', 'E3', 'A3'], duration: '8n.' },
  { notes: ['A2', 'E3', 'A3'], duration: '16n' },
  { notes: ['A2', 'E3', 'A3'], duration: '4n' },
  { notes: [], duration: '8n' },
  { notes: ['D3', 'A3', 'D4'], duration: '8n' },
  { notes: ['D3', 'A3', 'D4'], duration: '4n' },
  { notes: ['C3', 'G3', 'C4'], duration: '8n.' },
  { notes: ['C3', 'G3', 'C4'], duration: '16n' },
  { notes: ['C3', 'G3', 'C4'], duration: '4n' },
  { notes: [], duration: '8n' },
  { notes: ['F3', 'C4', 'F4'], duration: '8n' },
  { notes: ['F3', 'C4', 'F4'], duration: '4n' },
  { notes: ['A2', 'E3', 'A3'], duration: '8n.' },
  { notes: ['A2', 'E3', 'A3'], duration: '16n' },
  { notes: ['A2', 'E3', 'A3'], duration: '4n' },
  { notes: [], duration: '8n' },
  { notes: ['D3', 'A3', 'D4'], duration: '8n' },
  { notes: ['D3', 'A3', 'D4'], duration: '4n' },
  { notes: ['C3', 'G3', 'C4'], duration: '8n.' },
  { notes: ['C3', 'G3', 'C4'], duration: '16n' },
  { notes: ['C3', 'G3', 'C4'], duration: '4n' },
  { notes: [], duration: '8n' },
  { notes: ['F3', 'C4', 'F4'], duration: '8n' },
  { notes: ['F3', 'C4', 'F4'], duration: '4n' },
];

export const sweetChildOMineMelody = [
  { notes: ['C3'], duration: '8n' },
  { notes: ['C4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F3'], duration: '8n' },
  { notes: ['F4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['C3'], duration: '8n' },
  { notes: ['C4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F3'], duration: '8n' },
  { notes: ['F4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['C4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F3'], duration: '8n' },
  { notes: ['F4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['C4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F3'], duration: '8n' },
  { notes: ['F4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
];