export const sevenNationArmyMelody = [
  { time: 0, notes: ["E3"], duration: "4n." },
  { time: "0:1:2", notes: ["E3"], duration: "8n" },
  { time: "0:2", notes: ["G3"], duration: "8n." },
  { time: "0:2:3", notes: ["E3"], duration: "8n." },
  { time: "0:3:2", notes: ["D3"], duration: "8n" },
  { time: "1:0", notes: ["C3"], duration: "2n" },
  { time: "1:2", notes: ["B2"], duration: "2n" },
  { time: "2:0", notes: ["E3"], duration: "4n." },
  { time: "2:1:2", notes: ["E3"], duration: "8n" },
  { time: "2:2", notes: ["G3"], duration: "8n." },
  { time: "2:2:3", notes: ["E3"], duration: "8n." },
  { time: "2:3:2", notes: ["D3"], duration: "8n" },
  { time: "3:0", notes: ["C3"], duration: "8n." },
  { time: "3:0:3", notes: ["D3"], duration: "8n." },
  { time: "3:1:2", notes: ["C3"], duration: "8n" },
  { time: "3:2", notes: ["B2"], duration: "2n" },
];

export const babySharkMelody = [
  { time: 0, notes: ["C4"], duration: "8n" },
  { time: "0:0:2", notes: ["C4"], duration: "8n" },
  { time: "0:1", notes: ["C4"], duration: "8n" },
  { time: "0:1:2", notes: ["C4"], duration: "16n" },
  { time: "0:1:3", notes: ["C4"], duration: "8n" },
  { time: "0:2:1", notes: ["C4"], duration: "16n" },
  { time: "0:2:2", notes: ["C4"], duration: "8n" },
  { time: "0:3", notes: ["G3"], duration: "8n" },
  { time: "0:3:2", notes: ["A3"], duration: "8n" },
  { time: "1:0", notes: ["C4"], duration: "8n" },
  { time: "1:0:2", notes: ["C4"], duration: "8n" },
  { time: "1:1", notes: ["C4"], duration: "8n" },
  { time: "1:1:2", notes: ["C4"], duration: "16n" },
  { time: "1:1:3", notes: ["C4"], duration: "8n" },
  { time: "1:2:1", notes: ["C4"], duration: "16n" },
  { time: "1:2:2", notes: ["C4"], duration: "8n" },
  { time: "1:3", notes: ["G3"], duration: "8n" },
  { time: "1:3:2", notes: ["A3"], duration: "8n" },
  { time: "2:0", notes: ["C4"], duration: "8n" },
  { time: "2:0:2", notes: ["C4"], duration: "8n" },
  { time: "2:1", notes: ["C4"], duration: "8n" },
  { time: "2:1:2", notes: ["C4"], duration: "16n" },
  { time: "2:1:3", notes: ["C4"], duration: "8n" },
  { time: "2:2:1", notes: ["C4"], duration: "16n" },
  { time: "2:2:2", notes: ["C4"], duration: "8n" },
  { time: "2:3", notes: ["C4"], duration: "8n" },
  { time: "2:3:2", notes: ["C4"], duration: "8n" },
  { time: "3:0", notes: ["B3"], duration: "2n" },
  { time: "3:2", notes: ["G3"], duration: "4n" },
  { time: "3:3", notes: ["A3"], duration: "4n" },
];

export const inTheEndMelody = [
  { time: 0, notes: ["A3"], duration: "4n" },
  { time: "0:1", notes: ["E4"], duration: "4n" },
  { time: "0:2", notes: ["E4"], duration: "4n" },
  { time: "0:3", notes: ["C4"], duration: "4n" },
  { time: "1:0", notes: ["B3"], duration: "4n" },
  { time: "1:1", notes: ["B3"], duration: "4n" },
  { time: "1:2", notes: ["B3"], duration: "4n" },
  { time: "1:3", notes: ["B3"], duration: "8n" },
  { time: "1:3:2", notes: ["C4"], duration: "8n" },
  { time: "2:0", notes: ["A3"], duration: "4n" },
  { time: "2:1", notes: ["E4"], duration: "4n" },
  { time: "2:2", notes: ["E4"], duration: "4n" },
  { time: "2:3", notes: ["C4"], duration: "4n" },
  { time: "3:0", notes: ["B3"], duration: "4n" },
  { time: "3:1", notes: ["B3"], duration: "4n" },
  { time: "3:2", notes: ["B3"], duration: "4n" },
  { time: "3:3", notes: ["B3"], duration: "8n" },
  { time: "3:3:2", notes: ["C4"], duration: "8n" },
];

export const smellsLikeTeenSpiritMelody = [
  { time: 0, notes: ["A2", "E3", "A3"], duration: "8n." },
  { time: "0:0:3", notes: ["A2", "E3", "A3"], duration: "16n" },
  { time: "0:1", notes: ["A2", "E3", "A3"], duration: "4n." },
  { time: "0:2:2", notes: ["D3", "A3", "D4"], duration: "8n" },
  { time: "0:3", notes: ["D3", "A3", "D4"], duration: "4n" },
  { time: "1:0", notes: ["C3", "G3", "C4"], duration: "8n." },
  { time: "1:0:3", notes: ["C3", "G3", "C4"], duration: "16n" },
  { time: "1:1", notes: ["C3", "G3", "C4"], duration: "4n." },
  { time: "1:2:2", notes: ["F3", "C4", "F4"], duration: "8n" },
  { time: "1:3", notes: ["F3", "C4", "F4"], duration: "4n" },
  { time: "2:0", notes: ["A2", "E3", "A3"], duration: "8n." },
  { time: "2:0:3", notes: ["A2", "E3", "A3"], duration: "16n" },
  { time: "2:1", notes: ["A2", "E3", "A3"], duration: "4n." },
  { time: "2:2:2", notes: ["D3", "A3", "D4"], duration: "8n" },
  { time: "2:3", notes: ["D3", "A3", "D4"], duration: "4n" },
  { time: "3:0", notes: ["C3", "G3", "C4"], duration: "8n." },
  { time: "3:0:3", notes: ["C3", "G3", "C4"], duration: "16n" },
  { time: "3:1", notes: ["C3", "G3", "C4"], duration: "4n." },
  { time: "3:2:2", notes: ["F3", "C4", "F4"], duration: "8n" },
  { time: "3:3", notes: ["F3", "C4", "F4"], duration: "4n" },
];

export const sweetChildOMineMelody = [
  { time: 0, notes: ["C3"], duration: "8n" },
  { time: "0:0:2", notes: ["C4"], duration: "8n" },
  { time: "0:1", notes: ["G3"], duration: "8n" },
  { time: "0:1:2", notes: ["F3"], duration: "8n" },
  { time: "0:2", notes: ["F4"], duration: "8n" },
  { time: "0:2:2", notes: ["G3"], duration: "8n" },
  { time: "0:3", notes: ["E4"], duration: "8n" },
  { time: "0:3:2", notes: ["G3"], duration: "8n" },
  { time: "1:0", notes: ["C3"], duration: "8n" },
  { time: "1:0:2", notes: ["C4"], duration: "8n" },
  { time: "1:1", notes: ["G3"], duration: "8n" },
  { time: "1:1:2", notes: ["F3"], duration: "8n" },
  { time: "1:2", notes: ["F4"], duration: "8n" },
  { time: "1:2:2", notes: ["G3"], duration: "8n" },
  { time: "1:3", notes: ["E4"], duration: "8n" },
  { time: "1:3:2", notes: ["G3"], duration: "8n" },
  { time: "2:0", notes: ["D3"], duration: "8n" },
  { time: "2:0:2", notes: ["C4"], duration: "8n" },
  { time: "2:1", notes: ["G3"], duration: "8n" },
  { time: "2:1:2", notes: ["F3"], duration: "8n" },
  { time: "2:2", notes: ["F4"], duration: "8n" },
  { time: "2:2:2", notes: ["G3"], duration: "8n" },
  { time: "2:3", notes: ["E4"], duration: "8n" },
  { time: "2:3:2", notes: ["G3"], duration: "8n" },
  { time: "3:0", notes: ["D3"], duration: "8n" },
  { time: "3:0:2", notes: ["C4"], duration: "8n" },
  { time: "3:1", notes: ["G3"], duration: "8n" },
  { time: "3:1:2", notes: ["F3"], duration: "8n" },
  { time: "3:2", notes: ["F4"], duration: "8n" },
  { time: "3:2:2", notes: ["G3"], duration: "8n" },
  { time: "3:3", notes: ["E4"], duration: "8n" },
  { time: "3:3:2", notes: ["G3"], duration: "8n" },
];
