// Seven Nation Army
export const sevenNationArmyMelody = [
  { notes: ['E3'], duration: '4n.' },
  { notes: ['E3'], duration: '8n' },
  { notes: ['G3'], duration: '8n.' },
  { notes: ['E3'], duration: '8n.' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['C3'], duration: '2n' },
  { notes: ['B2'], duration: '2n' },
  { notes: ['E3'], duration: '4n.' },
  { notes: ['E3'], duration: '8n' },
  { notes: ['G3'], duration: '8n.' },
  { notes: ['E3'], duration: '8n.' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['C3'], duration: '8n.' },
  { notes: ['D3'], duration: '8n.' },
  { notes: ['C3'], duration: '8n' },
  { notes: ['B2'], duration: '2n' },
];

// Baby Shark
export const babySharkMelody = [
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['E3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['E3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '16n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F#3'], duration: '2n' },
  { notes: ['D3'], duration: '4n' },
  { notes: ['E3'], duration: '4n' },
];

export const inTheEndMelody = [
  { notes: ['E3'], duration: '4n' },
  { notes: ['B3'], duration: '4n' },
  { notes: ['B3'], duration: '4n' },
  { notes: ['G3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '4n' },
  { notes: ['F#3'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
]

export const smellsLikeTeenSpiritMelody = [
  { notes: ['A2', 'E3', 'A3'], duration: '8n.' },
  { notes: ['A2', 'E3', 'A3'], duration: '16n' },
  { notes: ['A2', 'E3', 'A3'], duration: '4n' },
  { notes: [], duration: '8n' },
  { notes: ['D3', 'A3', 'D4'], duration: '8n' },
  { notes: ['D3', 'A3', 'D4'], duration: '4n' },
  { notes: ['C3', 'G3', 'C4'], duration: '8n.' },
  { notes: ['C3', 'G3', 'C4'], duration: '16n' },
  { notes: ['C3', 'G3', 'C4'], duration: '4n' },
  { notes: [], duration: '8n' },
  { notes: ['F3', 'C4', 'F4'], duration: '8n' },
  { notes: ['F3', 'C4', 'F4'], duration: '4n' },
];

export const sweetChildOMineMelody = [
  { notes: ['C3'], duration: '8n' },
  { notes: ['C4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F3'], duration: '8n' },
  { notes: ['F4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['C3'], duration: '8n' },
  { notes: ['C4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F3'], duration: '8n' },
  { notes: ['F4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['C4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F3'], duration: '8n' },
  { notes: ['F4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['D3'], duration: '8n' },
  { notes: ['C4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['F3'], duration: '8n' },
  { notes: ['F4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
  { notes: ['E4'], duration: '8n' },
  { notes: ['G3'], duration: '8n' },
];