export const regularRhythm = [            // Measure
  { notes: [0, 2, 3], duration: '8n' },   // 1
  { notes: [2], duration: '8n' },
  { notes: [1, 2], duration: '8n' },
  { notes: [2], duration: '8n' },
  { notes: [0, 2], duration: '8n' },
  { notes: [0, 2], duration: '8n' },
  { notes: [1, 2], duration: '8n' },
  { notes: [2, 4], duration: '8n' },
  { notes: [0, 2], duration: '8n' },      // 2
  { notes: [2], duration: '8n' },
  { notes: [1, 2], duration: '8n' },
  { notes: [2], duration: '8n' },
  { notes: [0, 2], duration: '8n' },
  { notes: [0, 2], duration: '8n' },
  { notes: [1, 2], duration: '8n' },
  { notes: [2, 4], duration: '8n' },
  { notes: [0, 2, 3], duration: '8n' },   // 3
  { notes: [2], duration: '8n' },
  { notes: [1, 2], duration: '8n' },
  { notes: [2], duration: '8n' },
  { notes: [0, 2], duration: '8n' },
  { notes: [0, 2], duration: '8n' },
  { notes: [1, 2], duration: '8n' },
  { notes: [2, 4], duration: '8n' },
  { notes: [0, 2], duration: '8n' },      // 4
  { notes: [2], duration: '8n' },
  { notes: [1, 2], duration: '8n' },
  { notes: [2], duration: '8n' },
  { notes: [0, 2], duration: '8n' },
  { notes: [0, 2], duration: '8n' },
  { notes: [1, 2], duration: '8n' },
  { notes: [2, 4], duration: '8n' }
];

export const trapRhythm = [
  { notes: [0, 2, 3], duration: '16n' },    // 1
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 2], duration: '16n' },       // 2
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 2], duration: '16n' },        // 3
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 2], duration: '16n' },         // 4
  { notes: [2], duration: '16n' },
  { notes: [2, 4], duration: '16n' },
  { notes: [0, 2], duration: '16n' },
  { notes: [2, 4], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 2, 4], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 2, 4], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2, 4], duration: '16n' },
  { notes: [1, 2, 4], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 2, 4], duration: '16n' },
  { notes: [2], duration: '16n' },
];

export const claveRhythm = [
  { notes: [0, 3, 4], duration: '8n' },        // 1
  { notes: [2], duration: '16n' },
  { notes: [0, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 4], duration: '8n' },
  { notes: [0, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 4], duration: '8n' },        // 2
  { notes: [0, 2], duration: '16n' },
  { notes: [1, 4], duration: '8n' },
  { notes: [0, 2], duration: '16n' },
  { notes: [1, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 4], duration: '8n' },
  { notes: [1, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 4], duration: '8n' },        // 3
  { notes: [2], duration: '16n' },
  { notes: [0, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [0, 4], duration: '8n' },
  { notes: [0, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 4], duration: '8n' },        // 4
  { notes: [0, 2], duration: '16n' },
  { notes: [1, 4], duration: '8n' },
  { notes: [0, 2], duration: '16n' },
  { notes: [1, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
  { notes: [1, 4], duration: '8n' },
  { notes: [1, 4], duration: '8n' },
  { notes: [2], duration: '16n' },
  { notes: [2], duration: '16n' },
]