import {
  STOP,
  BIRD_IMG,
  CAT_IMG,
  DOG_IMG,
  CLAPPING_IMG,
  STOMPING_IMG,
  YEAH_IMG,

  BIRD_SOUND,
  CAT_SOUND,
  DOG_SOUND,
  CLAPPING_CONTINUOUS_SOUND,
  STOMPING_CONTINUOUS_SOUND,
  YEAH_CONTINUOUS_SOUND,
  CLAPPING_ONCE_SOUND,
  STOMPING_ONCE_SOUND,
  YEAH_ONCE_SOUND
} from "./sequenceMakerAssets";

const sounds = {
  CLAPPING_CONTINUOUS_SOUND,
  STOMPING_CONTINUOUS_SOUND,
  YEAH_CONTINUOUS_SOUND,
  CLAPPING_ONCE_SOUND,
  STOMPING_ONCE_SOUND,
  YEAH_ONCE_SOUND,
  DOG_SOUND,
  CAT_SOUND,
  BIRD_SOUND,
};

const images = {
  STOP,
  CLAPPING_IMG,
  STOMPING_IMG,
  YEAH_IMG,
  CAT_IMG,
  DOG_IMG,
  BIRD_IMG,
};

export { sounds, images };
